<script>
	import Breadcrumb from '$lib/components/Breadcrumb.svelte';
	import { initialRoles, initialPermisos, initialModulos } from '$lib/data/mockData.js';
	let rolSeleccionado = $state(1);
	let permisos = $derived(initialPermisos.filter((p) => p.rol_id === rolSeleccionado));
	const acciones = [['puede_crear', 'Crear', 'bi-plus-circle'], ['puede_leer', 'Consultar', 'bi-eye'], ['puede_actualizar', 'Actualizar', 'bi-pencil-square'], ['puede_eliminar', 'Eliminar', 'bi-trash']];
</script>
<svelte:head><title>Seguridad RBAC | SGPP</title></svelte:head>
<div class="container-fluid px-4 py-3"><Breadcrumb items={[{ label: 'Seguridad RBAC', href: '/seguridad' }]} />
	<header class="mb-4"><h2 class="h3 fw-bold mb-1"><i class="bi bi-shield-lock-fill text-primary me-2"></i>Seguridad y roles RBAC</h2><p class="text-muted mb-0">Matriz visual de permisos por jerarquía. La interfaz simula el control de acceso para esta evidencia.</p></header>
	<div class="row g-4"><div class="col-lg-4"><section class="card border-0 shadow-sm h-100"><div class="card-header bg-primary text-white"><h3 class="h5 mb-0">Jerarquía de usuarios</h3></div><div class="list-group list-group-flush">{#each initialRoles as rol}<button type="button" class="list-group-item list-group-item-action {rolSeleccionado === rol.id ? 'active' : ''}" onclick={() => rolSeleccionado = rol.id}><div class="d-flex justify-content-between align-items-center"><span class="fw-semibold"><i class="bi bi-person-circle me-2"></i>{rol.nombre}</span><span class="badge {rolSeleccionado === rol.id ? 'bg-white text-primary' : 'bg-primary'}">Nivel {rol.nivel_jerarquia}</span></div><small class="d-block mt-1 {rolSeleccionado === rol.id ? 'text-white-50' : 'text-muted'}">{rol.descripcion}</small></button>{/each}</div></section></div>
		<div class="col-lg-8"><section class="card border-0 shadow-sm"><div class="card-header bg-white p-3"><h3 class="h5 mb-1">Permisos de {initialRoles.find((r) => r.id === rolSeleccionado)?.nombre}</h3><small class="text-muted">Principio de menor privilegio: cada rol visualiza solo los módulos y acciones autorizados.</small></div><div class="table-responsive"><table class="table align-middle mb-0"><thead class="table-light"><tr><th class="ps-4">Módulo</th>{#each acciones as [, etiqueta]}<th class="text-center">{etiqueta}</th>{/each}</tr></thead><tbody>{#each initialModulos as modulo}{@const permiso = permisos.find((p) => p.modulo.toUpperCase() === modulo.codigo)}<tr><td class="ps-4"><i class="bi {modulo.icono} text-primary me-2"></i>{modulo.nombre}</td>{#each acciones as [campo, etiqueta, icono]}<td class="text-center">{#if permiso?.[campo]}<i class="bi {icono} text-success" aria-label={etiqueta}></i>{:else}<i class="bi bi-dash-lg text-muted" aria-label={'No autorizado: ' + etiqueta}></i>{/if}</td>{/each}</tr>{/each}</tbody></table></div></section>
			<div class="alert alert-info mt-4 mb-0"><i class="bi bi-info-circle-fill me-2"></i><strong>Demostración académica:</strong> el selector de rol del encabezado permite presentar una experiencia de usuario distinta; la validación real se conectará al API en una fase posterior.</div></div></div>
</div>
