<script>
	import Breadcrumb from '$lib/components/Breadcrumb.svelte';
	import { documentosStore, practicasStore } from '$lib/data/mockData.js';
	let mostrarFormulario = $state(false);
	let mensaje = $state('');
	let filtro = $state('todos');
	let nuevo = $state({ practica_id: 1, tipo_documento: 'Carta de Aceptación Empresarial', archivo_nombre: '' });
	let visibles = $derived($documentosStore.filter((d) => filtro === 'todos' || d.estado === filtro));
	function registrar(event) { event.preventDefault(); const p = $practicasStore.find((x) => x.id === Number(nuevo.practica_id)); documentosStore.update((l) => [{ id: l.length + 1, practica_id: Number(nuevo.practica_id), estudiante_nombre: p?.estudiante_nombre ?? 'Estudiante', tipo_documento: nuevo.tipo_documento, archivo_nombre: nuevo.archivo_nombre || 'Documento_soporte.pdf', fecha_subida: '2026-09-11', estado: 'Pendiente Revisión', observaciones: 'Soporte cargado para revisión.' }, ...l]); mensaje = 'Documento agregado a la bandeja de revisión.'; mostrarFormulario = false; }
</script>
<svelte:head><title>Documentos | SGPP</title></svelte:head>
<div class="container-fluid px-4 py-3"><Breadcrumb items={[{ label: 'Documentos', href: '/documentos' }]} />
	<header class="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-3 mb-4"><div><h2 class="h3 fw-bold mb-1"><i class="bi bi-folder2-open text-primary me-2"></i>Gestor Documental</h2><p class="text-muted mb-0">Control de cartas, ARL, planes de trabajo y soportes de práctica.</p></div><button class="btn btn-primary shadow-sm" type="button" onclick={() => mostrarFormulario = !mostrarFormulario}><i class="bi bi-upload me-2"></i>{mostrarFormulario ? 'Cancelar carga' : 'Cargar soporte'}</button></header>
	{#if mensaje}<div class="alert alert-success alert-dismissible fade show" role="alert">{mensaje}<button class="btn-close" type="button" aria-label="Cerrar" onclick={() => mensaje = ''}></button></div>{/if}
	{#if mostrarFormulario}<section class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><form onsubmit={registrar}><div class="row g-3 align-items-end"><div class="col-md-4"><label class="form-label" for="doc-practica">Práctica</label><select id="doc-practica" class="form-select" bind:value={nuevo.practica_id}>{#each $practicasStore as p}<option value={p.id}>{p.estudiante_nombre}</option>{/each}</select></div><div class="col-md-4"><label class="form-label" for="tipo-doc">Tipo de documento</label><select id="tipo-doc" class="form-select" bind:value={nuevo.tipo_documento}><option>Carta de Aceptación Empresarial</option><option>Afiliación ARL Vigente</option><option>Plan de Trabajo Concertado</option><option>Informe Final</option></select></div><div class="col-md-4"><label class="form-label" for="archivo">Nombre del archivo</label><input id="archivo" class="form-control" required placeholder="Ejemplo.pdf" bind:value={nuevo.archivo_nombre}></div><div class="col-12 text-end"><button type="submit" class="btn btn-success"><i class="bi bi-cloud-arrow-up me-2"></i>Registrar soporte</button></div></div></form></div></section>{/if}
	<section class="card border-0 shadow-sm"><div class="card-header bg-white p-3 d-flex flex-column flex-sm-row justify-content-between gap-2"><div><h3 class="h5 mb-1">Bandeja de documentos</h3><small class="text-muted">Los archivos se muestran como evidencia visual; no hay conexión a API en esta entrega.</small></div><select class="form-select form-select-sm" style="max-width: 220px" aria-label="Filtrar documentos" bind:value={filtro}><option value="todos">Todos los estados</option><option>Aprobado</option><option>Pendiente Revisión</option></select></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th class="ps-4">Estudiante</th><th>Documento</th><th>Archivo</th><th>Fecha</th><th>Observaciones</th><th>Estado</th></tr></thead><tbody>{#each visibles as d}<tr><td class="ps-4 fw-semibold">{d.estudiante_nombre}</td><td>{d.tipo_documento}</td><td><i class="bi bi-file-earmark-pdf text-danger me-2"></i>{d.archivo_nombre}</td><td>{d.fecha_subida}</td><td><small class="text-muted">{d.observaciones}</small></td><td><span class="badge {d.estado === 'Aprobado' ? 'bg-success-subtle text-success border border-success-subtle' : 'bg-warning-subtle text-warning border border-warning-subtle'}">{d.estado}</span></td></tr>{/each}</tbody></table></div></section>
</div>
